"""Generate only validated, bounded nginx configuration."""
import hashlib
import ipaddress
import json
from pathlib import Path

from .config import validate, route_targets


def digest(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True).encode()).hexdigest()[:16]


def ip_literal(value):
    return f"[{value}]" if ":" in value else value


def render(config, generation, cache_dir="/cache", run_dir="/run/ambergate", port=80,
           control_port=8084, mime_types="/etc/nginx/mime.types"):
    c = validate(config)
    s = c["settings"]
    # These paths are administrator-controlled environment values, not web input.
    for value in (cache_dir, run_dir, mime_types):
        if not str(value).startswith("/") or any(x in str(value) for x in ('"', '\\', '\n', '\r', '$')):
            raise ValueError("Runtime paths must be absolute and contain no nginx metacharacters")
    lines = [
        "# Generated by AmberGate. Edit through the admin panel.",
        "worker_processes 2;", "worker_shutdown_timeout 30s;",
        f'pid "{run_dir}/nginx.pid";', "error_log /dev/stderr warn;",
        "events { worker_connections 2048; }", "http {",
        f'    include "{mime_types}";', "    default_type application/octet-stream;",
        "    server_tokens off;", "    sendfile on;", "    keepalive_timeout 65s;",
        "    client_header_timeout 10s;", "    client_body_timeout 15s;",
        "    send_timeout 30s;", "    reset_timedout_connection on;",
        f"    client_max_body_size {s['body_mb']}m;",
        f'    client_body_temp_path "{run_dir}/body";',
        f'    proxy_temp_path "{run_dir}/proxy";',
        "    log_format ambergate '$remote_addr [$time_local] $host '",
        "                       '\"$request_method $uri $server_protocol\" $status '",
        "                       '$body_bytes_sent rt=$request_time upstream=$upstream_addr '",
        "                       'cache=$upstream_cache_status';",
        "    access_log /dev/stdout ambergate;",
        "    log_format telemetry escape=json '{\"time\":\"$msec\",\"host\":\"$server_name\",'",
        "        '\"route\":\"$ambergate_route\",\"status\":$status,\"bytes\":$body_bytes_sent,'",
        "        '\"seconds\":$request_time,\"cache\":\"$upstream_cache_status\",'",
        "        '\"limit\":\"$limit_req_status/$limit_conn_status\"}';",
        f'    access_log "syslog:server=unix:{run_dir}/metrics.sock,tag=ambergate,nohostname" telemetry;',
        "    resolver " + " ".join(ip_literal(x) for x in s["resolvers"]) + " valid=10s ipv6=off;",
        "    resolver_timeout 3s;",
        '    map $http_upgrade $connection_upgrade { default upgrade; "" ""; }',
        '    map $http_authorization $has_auth { default 1; "" 0; }',
        '    map $http_cookie $has_cookie { default 1; "" 0; }',
        '    map $request_method $unsafe_method { default 1; GET 0; HEAD 0; }',
        '    map $http_upgrade $has_upgrade { default 1; "" 0; }',
        '    map $args $signed_request { default 0; ~*(^|&)(x-amz-[^=]*|signature|awsaccesskeyid|token|access_token)= 1; }',
        '    map $http_cache_control $request_no_cache { default 0; ~*(no-cache|no-store) 1; }',
        '    geo $realip_remote_addr $trusted_peer {', "        default 0;",
    ]
    for network in s["trusted_proxies"]:
        lines.append(f"        {ipaddress.ip_network(network, strict=False)} 1;")
    lines += ["    }", "    map $proxy_host $ambergate_route {", '        default "-";']
    for host in c["hosts"]:
        if host["enabled"]:
            for route in host["routes"]:
                upstream = "up_" + digest([host["id"], route])
                lines.append(f'        {upstream} "{route["path"]}";')
    lines += ["    }", '    map "$trusted_peer:$http_x_forwarded_proto" $external_scheme {',
              "        default $scheme;", '        "1:https" https;', '        "1:http" http;', "    }"]
    if s["trusted_proxies"]:
        lines += [f"    set_real_ip_from {ipaddress.ip_network(x, strict=False)};" for x in s["trusted_proxies"]]
        lines += ["    real_ip_header X-Forwarded-For;", "    real_ip_recursive on;"]
    if s["rate_rps"]:
        lines += [f"    limit_req_zone $binary_remote_addr zone=global_rate_{s['rate_rps']}:10m rate={s['rate_rps']}r/s;"]
    lines += ["    limit_conn_zone $binary_remote_addr zone=global_conn:10m;",
              "    limit_req_status 429;", "    limit_conn_status 429;",
              f'    proxy_cache_path "{cache_dir}" levels=1:2 keys_zone=ambergate_cache:16m '
              f"max_size={s['cache_mb']}m inactive=60m use_temp_path=off;",
              "    server {", f"        listen 127.0.0.1:{control_port};", "        access_log off;",
              f'        location = /generation {{ default_type text/plain; return 200 "{generation}"; }}',
              "        location = /status { stub_status; }",
              "        location / { return 404; }", "    }",
              f"    server {{ listen {port} default_server; server_name _; return 404; }}"]
    for host in c["hosts"]:
        if not host["enabled"]:
            continue
        for route in host["routes"]:
            upstream = "up_" + digest([host["id"], route])
            if not route_targets(route):
                continue
            if route["rate_rps"]:
                lines.append(f"    limit_req_zone $binary_remote_addr zone=rate_{upstream}:1m rate={route['rate_rps']}r/s;")
            lines += [f"    upstream {upstream} {{", f"        zone {upstream} 64k;"]
            if route["balance"] != "round_robin":
                lines.append(f"        {route['balance']};")
            if all(t["backup"] for t in route_targets(route)):
                # Keep Docker backup members usable while all primary replicas
                # are stopped. The placeholder cannot receive any traffic.
                lines.append("        server 127.0.0.1:1 down;")
            for target in route_targets(route):
                address = target["address"]
                try:
                    ipaddress.ip_address(address)
                    resolve = ""
                except ValueError:
                    resolve = " resolve"
                backup = " backup" if target["backup"] else ""
                lines.append(f"        server {ip_literal(address)}:{target['port']} weight={target['weight']}"
                             f" max_fails=3 fail_timeout=10s{backup}{resolve};")
            lines += ["        keepalive 32;", "    }"]
        lines += ["    server {", f"        listen {port};", f"        server_name {host['domain'].lower()};",
                  "        if ($request_method !~ ^(GET|HEAD|POST|PUT|PATCH|DELETE|OPTIONS)$) { return 405; }"]
        if s["block_dotfiles"]:
            lines += ['        if ($uri ~ "(^|/)\\.(?!well-known(?:/|$))") { return 404; }']
        if s["connections_per_ip"]:
            lines.append(f"        limit_conn global_conn {s['connections_per_ip']};")
        for route in host["routes"]:
            upstream = "up_" + digest([host["id"], route])
            path = route["path"]
            locations = ["/"] if path == "/" else ["= " + path, "^~ " + path + "/"]
            for location in locations:
                lines += [f"        location {location} {{"]
                if not route_targets(route):
                    lines += [f'            set $ambergate_route "{path}";', "            return 503;", "        }"]
                    continue
                if s["rate_rps"]:
                    burst = f" burst={s['rate_burst']} nodelay" if s["rate_burst"] else ""
                    lines.append(f"            limit_req zone=global_rate_{s['rate_rps']}{burst};")
                if route["rate_rps"]:
                    burst = f" burst={route['rate_burst']} nodelay" if route["rate_burst"] else ""
                    lines.append(f"            limit_req zone=rate_{upstream}{burst};")
                lines += ["            proxy_http_version 1.1;",
                          "            proxy_set_header Host $http_host;",
                          "            proxy_set_header X-Real-IP $remote_addr;",
                          "            proxy_set_header X-Forwarded-For $remote_addr;",
                          "            proxy_set_header X-Forwarded-Host $http_host;",
                          "            proxy_set_header X-Forwarded-Proto $external_scheme;",
                          '            proxy_set_header Forwarded "";',
                          '            proxy_set_header X-Forwarded-Port "";',
                          "            proxy_connect_timeout 5s;",
                          f"            proxy_read_timeout {route['timeout']}s;",
                          f"            proxy_send_timeout {route['timeout']}s;",
                          "            proxy_next_upstream error timeout http_502 http_503 http_504;",
                          "            proxy_next_upstream_tries 3;"]
                if route["body_mb"]:
                    lines.append(f"            client_max_body_size {route['body_mb']}m;")
                if route["websocket"]:
                    lines += ["            proxy_set_header Upgrade $http_upgrade;",
                              "            proxy_set_header Connection $connection_upgrade;"]
                else:
                    lines += ['            proxy_set_header Upgrade "";', '            proxy_set_header Connection "";']
                if s["security_headers"]:
                    lines += ["            add_header X-Content-Type-Options nosniff always;",
                              "            add_header Referrer-Policy strict-origin-when-cross-origin always;"]
                if route["cache"]:
                    # Namespace by route content: changed destinations cannot reuse old responses.
                    lines += ["            proxy_cache ambergate_cache;",
                              f'            proxy_cache_key "{upstream}|$external_scheme|$http_host|$request_uri";',
                              f"            proxy_cache_valid 200 301 302 {route['cache_ttl']}s;",
                              "            proxy_cache_methods GET HEAD;",
                              "            proxy_cache_lock on;",
                              "            proxy_cache_bypass $has_auth $has_cookie $unsafe_method $signed_request $has_upgrade $request_no_cache;",
                              "            proxy_no_cache $has_auth $has_cookie $unsafe_method $signed_request $has_upgrade $request_no_cache $upstream_http_set_cookie;",
                              "            add_header X-AmberGate-Cache $upstream_cache_status always;",
                              "            add_header X-Gateway-Cache $upstream_cache_status always;"]
                # A URI on proxy_pass replaces the matched prefix, including exact /api.
                suffix = "/" if route["strip_prefix"] and path != "/" else ""
                lines += [f"            proxy_pass http://{upstream}{suffix};", "        }"]
        if not any(r["path"] == "/" for r in host["routes"]):
            lines += ["        location / { return 404; }"]
        lines += ["    }"]
    lines += ["}", ""]
    return "\n".join(lines)
