#!/usr/bin/env bash
# First-start installer for Debian / Ubuntu. No curl | sh and no package removals.
set -Eeuo pipefail
umask 077

log() { printf '\n[AmberGate] %s\n' "$*"; }
die() { printf '\n[AmberGate] ERROR: %s\n' "$*" >&2; exit 1; }
usage() {
  cat <<'HELP'
Usage: sudo bash first-start.sh [options]

Install missing dependencies and start one AmberGate container.
Supported: Debian 12/13, Ubuntu 22.04/24.04/26.04; amd64 / arm64.
Existing Docker, Compose, configuration and data are preserved.

  --dir PATH          Installation directory (default: /opt/ambergate)
  --admin-bind IP     Admin listen IP on a new install (default: 127.0.0.1)
  --admin-port PORT   Admin port on a new install (default: 8083)
  --http-port PORT    AmberGate HTTP port on a new install (default: 80)
  --with-docker      Mount the Docker socket for optional container discovery
  --socket PATH      Local Docker socket (default: /var/run/docker.sock)
  --no-start         Install dependencies and prepare files, without starting AmberGate
  --check            Read-only dependency check; exit 1 if something is missing
  -h, --help         Show this help

Ports and --with-docker apply only when creating compose.yaml.
The admin password is generated by AmberGate and printed once in container logs.
Enable Docker discovery in the panel after mounting the socket.
HELP
}
main() {
  local install_dir=/opt/ambergate admin_bind=127.0.0.1 admin_port=8083 http_port=80
  local socket_path=/var/run/docker.sock with_docker=0 no_start=0 check_only=0
  local original_args=("$@")
  while (($#)); do
    case "$1" in
      --dir|--admin-bind|--admin-port|--http-port|--socket)
        (($# >= 2)) && [[ -n "$2" && "$2" != --* ]] || die "Missing value for $1"
        case "$1" in
          --dir) install_dir=$2;; --admin-bind) admin_bind=$2;;
          --admin-port) admin_port=$2;; --http-port) http_port=$2;; --socket) socket_path=$2;;
        esac
        shift 2;;
      --with-docker) with_docker=1; shift;;
      --no-start) no_start=1; shift;;
      --check) check_only=1; shift;;
      -h|--help) usage; return;;
      *) die "Unknown option: $1 (use --help)";;
    esac
  done
  [[ $(uname -s) == Linux ]] || die "This installer supports Linux servers. Use Docker Compose directly on macOS/Windows."
  [[ $install_dir == /* && $install_dir != / && $install_dir != *$'\n'* && $install_dir != *'$'* ]] || die "--dir must be an absolute directory, without newlines or dollar signs."
  [[ $socket_path == /* && $socket_path == *.sock && $socket_path != *$'\n'* && $socket_path != *'$'* ]] || die "--socket must be an absolute .sock path."
  for port in "$admin_port" "$http_port"; do
    [[ $port =~ ^[0-9]{1,5}$ ]] && ((10#$port >= 1 && 10#$port <= 65535)) || die "Ports must be between 1 and 65535."
  done
  ((10#$admin_port != 10#$http_port)) || die "Admin and HTTP ports must differ."
  [[ -r /etc/os-release ]] || die "Cannot detect this Linux distribution."
  # shellcheck disable=SC1091
  . /etc/os-release
  case "${ID:-}:${VERSION_ID:-}" in
    debian:12|debian:13|ubuntu:22.04|ubuntu:24.04|ubuntu:26.04) ;;
    *) die "Supported systems: Debian 12/13 and Ubuntu 22.04/24.04/26.04. Use Compose directly on other systems.";;
  esac
  case "$(uname -m)" in x86_64|aarch64|arm64) ;; *) die "The AmberGate image supports amd64 and arm64.";; esac
  local docker_cmd=(docker --host "unix://$socket_path")
  if ((check_only)); then
    local missing=0 component
    for component in curl python3 docker; do
      if command -v "$component" >/dev/null; then log "$component: installed"; else log "$component: MISSING"; missing=1; fi
    done
    if dpkg-query -W -f='${Status}' ca-certificates 2>/dev/null | grep -q 'install ok installed'; then log 'CA certificates: installed'; else log 'CA certificates: MISSING'; missing=1; fi
    if "${docker_cmd[@]}" compose version >/dev/null 2>&1; then log 'Compose plugin: installed'; else log 'Compose plugin: MISSING'; missing=1; fi
    if "${docker_cmd[@]}" info >/dev/null 2>&1; then log 'Docker daemon: accessible'; else log 'Docker daemon: unavailable or access denied'; missing=1; fi
    return "$missing"
  fi
  if ((EUID != 0)); then
    command -v sudo >/dev/null || die 'Run this script as root (sudo is not installed).'
    exec sudo bash "${BASH_SOURCE[0]}" "${original_args[@]}"
  fi
  if [[ $install_dir == /opt/ambergate && ! -e $install_dir/compose.yaml && -e /opt/nginx-scale-gw/compose.yaml ]]; then
    die 'An existing installation was found at /opt/nginx-scale-gw. Update its image to ghcr.io/gadmin2151/ambergate:latest, keeping its data mounts, then rerun with --dir /opt/nginx-scale-gw. See the README migration guide.'
  fi
  local packages=() component
  for component in curl ca-certificates python3; do
    if ! dpkg-query -W -f='${Status}' "$component" 2>/dev/null | grep -q 'install ok installed'; then packages+=("$component"); fi
  done
  if ((${#packages[@]})); then
    log "Installing missing components: ${packages[*]}"
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-remove --no-install-recommends "${packages[@]}"
  fi
  python3 - "$admin_bind" <<'PY' || die '--admin-bind must be an IPv4 or IPv6 address.'
import ipaddress,sys
ipaddress.ip_address(sys.argv[1])
PY
  if ! command -v docker >/dev/null; then
    # Do not replace an existing container runtime or remove conflicting packages.
    for component in docker.io podman-docker containerd runc; do
      if dpkg-query -W -f='${Status}' "$component" 2>/dev/null | grep -q 'install ok installed'; then
        die "Existing $component package detected. Configure Docker Engine manually; this script will not remove it."
      fi
    done
    setup_docker_repository "$ID" "${UBUNTU_CODENAME:-${VERSION_CODENAME:-}}"
    log 'Installing Docker Engine and Compose from the official Docker repository'
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-remove --no-install-recommends docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  else
    log 'Docker is already installed'
  fi
  if ! "${docker_cmd[@]}" compose version >/dev/null 2>&1; then
    log 'Installing the missing Compose plugin'
    apt-get update
    if apt-cache show docker-compose-v2 >/dev/null 2>&1; then
      DEBIAN_FRONTEND=noninteractive apt-get install -y --no-remove --no-install-recommends docker-compose-v2
    else
      if ! apt-cache show docker-compose-plugin >/dev/null 2>&1; then
        setup_docker_repository "$ID" "${UBUNTU_CODENAME:-${VERSION_CODENAME:-}}"
      fi
      DEBIAN_FRONTEND=noninteractive apt-get install -y --no-remove --no-install-recommends docker-compose-plugin
    fi
  else
    log 'Compose is already installed'
  fi
  "${docker_cmd[@]}" compose version >/dev/null || die 'Compose plugin is not usable.'
  if ! "${docker_cmd[@]}" info >/dev/null 2>&1; then
    [[ $socket_path == /var/run/docker.sock ]] || die "Start the Docker daemon for $socket_path and rerun."
    command -v systemctl >/dev/null || die 'Start the Docker daemon manually and rerun.'
    log 'Starting Docker and enabling it at boot'
    systemctl enable --now docker
    local ready=0
    for ((attempt=0; attempt<30; attempt++)); do
      if "${docker_cmd[@]}" info >/dev/null 2>&1; then ready=1; break; fi
      sleep 1
    done
    ((ready)) || die 'Docker did not become ready. Check: journalctl -u docker'
  fi
  [[ -S $socket_path ]] || die "Docker socket not found: $socket_path"
  install -d -m 0750 "$install_dir"
  if [[ -e $install_dir/compose.yaml || -L $install_dir/compose.yaml ]]; then
    log "Keeping existing $install_dir/compose.yaml and all data"
  else
    log "Preparing $install_dir"
    python3 - "$install_dir" "$admin_bind" "$admin_port" "$http_port" "$with_docker" "$socket_path" <<'PY'
import json,os,pathlib,sys
root=pathlib.Path(sys.argv[1]); address=sys.argv[2]
if ':' in address: address='['+address+']'
service={'image':'ghcr.io/gadmin2151/ambergate:latest','restart':'unless-stopped',
 'ports':[f'{int(sys.argv[4])}:80',f'{address}:{int(sys.argv[3])}:8083'],
 'volumes':['./data:/data','./cache:/cache','./run:/run/ambergate'],
 'networks':['ambergate'],'stop_grace_period':'35s',
 'logging':{'driver':'json-file','options':{'max-size':'10m','max-file':'3'}}}
if sys.argv[5]=='1':
 service['volumes'].append({'type':'bind','source':sys.argv[6],'target':'/var/run/docker.sock','read_only':True,'bind':{'create_host_path':False}})
 service['environment']={'AMBERGATE_DOCKER_SOCKET':'/var/run/docker.sock'}
for name in ['data','cache','run']: (root/name).mkdir(mode=0o750,exist_ok=True)
# JSON is valid YAML. Exclusive creation protects an existing installation.
with (root/'compose.yaml').open('x') as f:
 json.dump({'services':{'ambergate':service},'networks':{'ambergate':{'name':'ambergate'}}},f,indent=2);f.write('\n')
PY
  fi
  local compose=("${docker_cmd[@]}" compose --project-directory "$install_dir" -f "$install_dir/compose.yaml")
  "${compose[@]}" config --quiet
  local service=ambergate services
  services=$("${compose[@]}" config --services)
  if ! grep -qx ambergate <<<"$services"; then
    grep -qx gateway <<<"$services" || die 'Compose must contain an ambergate service (or the legacy gateway service).'
    service=gateway
  fi
  if ((no_start)); then log "Ready. Start with: docker compose --project-directory $install_dir -f $install_dir/compose.yaml up -d"; return; fi
  "${compose[@]}" up --help | grep -q -- '--wait' || die 'Compose is too old: install a version supporting up --wait.'
  log 'Starting AmberGate and waiting for its health check'
  if ! "${compose[@]}" up -d --wait --wait-timeout 60; then
    die "AmberGate did not become healthy. Check ports and run: docker compose -f $install_dir/compose.yaml logs --tail 80"
  fi
  log 'AmberGate is healthy'
  "${compose[@]}" ps
  log "Admin endpoint (use an SSH tunnel for loopback):"
  "${compose[@]}" port "$service" 8083
  log "Initial password: sudo docker compose -f $install_dir/compose.yaml logs $service"
  log "Configuration and data: $install_dir"
}
setup_docker_repository() {
  local distro=$1 codename=$2
  [[ $codename =~ ^[a-z]+$ ]] || die 'Cannot detect the release codename for the Docker repository.'
  # Official instructions: https://docs.docker.com/engine/install/debian/ (or /ubuntu/).
  if grep -Rqs "download.docker.com/linux/$distro" /etc/apt/sources.list /etc/apt/sources.list.d/; then
    log 'Using the existing Docker apt repository'
  else
    install -d -m 0755 /etc/apt/keyrings
    local key_tmp
    key_tmp=$(mktemp)
    if ! curl --fail --silent --show-error --location --proto '=https' --tlsv1.2 --connect-timeout 15 --max-time 120 "https://download.docker.com/linux/$distro/gpg" -o "$key_tmp"; then
      rm -f "$key_tmp"; die 'Could not download the Docker signing key.'
    fi
    install -m 0644 "$key_tmp" /etc/apt/keyrings/ambergate-docker.asc
    rm -f "$key_tmp"
    printf 'Types: deb\nURIs: https://download.docker.com/linux/%s\nSuites: %s\nComponents: stable\nArchitectures: %s\nSigned-By: /etc/apt/keyrings/ambergate-docker.asc\n' "$distro" "$codename" "$(dpkg --print-architecture)" > /etc/apt/sources.list.d/ambergate-docker.sources
    chmod 0644 /etc/apt/sources.list.d/ambergate-docker.sources
  fi
  apt-get update
}
if [[ ${BASH_SOURCE[0]} == "$0" ]]; then main "$@"; fi
